Flixte.Web/Controllers/StationController.cs
using Flixte.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flixte.Web.Controllers
{
    public class StationController : BaseController
    {
        // GET: Station
        public ActionResult Index()
        {
            ViewData["ListaRetorno"] = string.Join(",",Flixte.Core.Integration.YoutubeService.FindByFilter("tapioca").ToArray());
            return View(Flixte.Core.Services.EstacaoService.FindAllWithInactive());
        }

        // GET: Station/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Station/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Station/Create
        [HttpPost]
        public ActionResult Create(Estacao model)
        {
            try
            {
                model.Ativo = true;
                model.Data = DateTime.Now;
                model.Destaque = false;
                model.Excluido = false;
                
                model.IDUsuario = GetUserID();
                model.Privado = false;
                model.Senha = null;
                model.Tags = null;
                model.URLLogo = null;
                model.Users = 0;
                model.Views = 0;
                Flixte.Core.Services.EstacaoService.Insert(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string erro = ex.Message;
                return View();
            }
        }

        // GET: Station/Edit/5
        public ActionResult Edit(int id)
        {
            return View(Flixte.Core.Services.EstacaoService.GetEstacao(id));
        }

        // POST: Station/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Estacao model)
        {
            try
            {
                model.ID = id;
                Flixte.Core.Services.EstacaoService.Update(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Station/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Station/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Flixte.Core.Services.EstacaoService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Flixte.Web/Views/Station/Create.cshtml
@model Flixte.Core.Models.Estacao
@{
    ViewBag.Title = "Criar Estação";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "Station", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Crie uma nova estação.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Nome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Descricao, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Descricao, new { @class = "form-control" })
        </div>
    </div>    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Criar" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Flixte.Web/Views/Station/Index.cshtml
@model List<Flixte.Core.Models.Estacao>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
Stations
<br/><br/>
@{WriteLiteral(ViewData["ListaRetorno"]);}
<a href="/Station/Create">Criar Estação</a>
<table width="100%">
    <tr>
        <td>Nome</td>
        <td>Excluir</td>
    </tr>
    
@foreach (var estacao in Model)
{
    <tr>
        <td><a href="/Station/Edit?id=@estacao.ID">@estacao.Nome</a></td>
        <td><a href="/Station/Delete?id=@estacao.ID">Excluir</a></td>
    </tr>
}
</table>